NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

VERSION="2.6.0"

ACCOUNTS=[
"",
"",
"",
""
]

[DOCUMENTATION]
ORG_NAME="POYE Network"
ORG_DBA="POYE"
ORG_URL="https://poye.xyz"
ORG_LOGO="https://poye.xyz/logo.png"
ORG_DESCRIPTION="POYE Network champions Sorobanâ€™s belief that Smart Contract will have a massive positive impact on Stellar's future to humanity. And as Soroban paves the path towards decentralization and longevity, $POYE is here to spread optimism all along the way."
ORG_PHYSICAL_ADDRESS="XLM, Paris"
ORG_GITHUB="poye-network"
ORG_TWITTER="poye_token"
ORG_OFFICIAL_EMAIL="info@poye.xyz"

[[CURRENCIES]]
code="POYE"
issuer="GCANJQJUFIWG7TXKCAJPG726KWW5CXISB2KM2MZRYLVV6AMZENZQN2ZE"
display_decimals=7
name="POYE"
desc="Xaipe to losses! Hop on the most memeable fun token fueled by pure memetic power and good vibes. Ownership renounced and full liquidity locked."
is_asset_anchored=false
conditions="There will only ever be 1,000,000,000 POYE in existence. Join the moon mission and keep spreading the news!"
image="https://poye.xyz/logo.png"
fixed_number=1000000000
status="live"

[[PRINCIPALS]]
name="Poye Network"
email="info@poye.xyz"
twitter="poye_token"
telegram="poye_token"
